# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schuelerID', models.PositiveSmallIntegerField()),
                ('vorname', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('geburtstag', models.DateTimeField()),
                ('Wohnort', models.CharField(max_length=15)),
                ('Schulende', models.PositiveSmallIntegerField()),
                ('Lerngruppe', models.CharField(choices=[('Hydrix', 'Hydrix'), ('Panthera', 'Panthera'), ('Natrix', 'Natrix'), ('Orxgym', 'Orxgym'), ('Lupus', 'Lupus')], max_length=15)),
            ],
        ),
    ]
