# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='geburtstag',
            field=models.DateField(),
        ),
    ]
